language: node_js
node_js:
      - "6"
      - "5"
      - "4"
#before_install: npm install --dev
script: npm test 
notifications:
  email:
    recipients:
      - moshe.maor@kaltura.com
      - jess.portnoy@kaltura.com
    on_success: change
    on_failure: always
