language: node_js
node_js:
      - "6"
      - "5"
      - "4"
<<<<<<< HEAD
script: npm test
=======
#before_install: npm install --dev
script: npm test 
>>>>>>> 80d760ec9e82130bea8114dc9ffa74a74ecf590a
notifications:
  email:
    recipients:
      - moshe.maor@kaltura.com
      - jess.portnoy@kaltura.com
    on_success: change
    on_failure: always
